# Generated by Django 3.2.4 on 2021-06-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=24)),
                ('geo_coordinates', models.CharField(max_length=24, unique=True)),
                ('temperature', models.CharField(max_length=8)),
                ('wind', models.CharField(max_length=64)),
                ('cloudiness', models.CharField(max_length=64)),
                ('pressure', models.CharField(max_length=12)),
                ('humidity', models.CharField(max_length=8)),
                ('sunrise', models.CharField(max_length=8)),
                ('sunset', models.CharField(max_length=8)),
                ('requested_time', models.CharField(max_length=24)),
            ],
        ),
    ]
