name: Weather API CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
      run: |
        cd api
        pytest
    - name: Merge develop -> master
      if: success()
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: develop
        target_branch: master
        github_token: ${{ github.token }}
